// One-shot catalog importer: replaces the demo decks with the real R2-backed catalog.
//
// Data comes from convex/catalogData.ts (generated by scripts/build-catalog.mjs and
// bundled into the deployment — no CLI args). These are internal functions: not exposed
// to clients, and runnable without an authed user via:
//
//   npx convex run importCatalog:run            # dev deployment
//   npx convex run --prod importCatalog:run     # production
//
// Idempotent: each run wipes curated content first, then re-inserts everything.

import { internalMutation, internalAction } from "./_generated/server";
import { internal } from "./_generated/api";
import { v } from "convex/values";
import { catalog } from "./catalogData";

// Delete a bounded batch of curated content so we never blow the per-mutation write
// budget. The action below calls this until it returns deleted: 0.
export const wipeBatch = internalMutation({
  args: { budget: v.optional(v.number()) },
  handler: async (ctx, { budget = 400 }) => {
    let left = budget;

    // Core curated content + draw/completion history that references it.
    const tables = ["cards", "decks", "drawHistory", "deckCompletions"] as const;
    for (const t of tables) {
      if (left <= 0) break;
      const rows = await ctx.db.query(t).take(left);
      for (const r of rows) await ctx.db.delete(r._id);
      left -= rows.length;
    }

    // Only curated favorites / scheduled shares — leave studio rows intact.
    const kinded = ["favorites", "scheduledShares"] as const;
    for (const t of kinded) {
      if (left <= 0) break;
      const rows = await ctx.db
        .query(t)
        .filter((q) => q.eq(q.field("kind"), "curated"))
        .take(left);
      for (const r of rows) await ctx.db.delete(r._id);
      left -= rows.length;
    }

    return { deleted: budget - left };
  },
});

// Insert a single deck (by index into the bundled catalog) and its cards.
export const importOneDeck = internalMutation({
  args: { deckIndex: v.number() },
  handler: async (ctx, { deckIndex }) => {
    const deck = catalog.decks[deckIndex];
    if (!deck) throw new Error(`No deck at index ${deckIndex}`);

    const deckId = await ctx.db.insert("decks", {
      title: deck.title,
      description: deck.description,
      coverImageUrl: deck.coverImageUrl,
      category: deck.category,
      totalCards: deck.totalCards,
      isActive: deck.isActive,
      colorTheme: deck.colorTheme,
    });

    const sorted = [...deck.cards].sort((a, b) => a.cardNumber - b.cardNumber);
    for (const c of sorted) {
      await ctx.db.insert("cards", {
        deckId,
        imageUrl: c.imageUrl,
        quote: c.quote,
        description: c.description,
        cardNumber: c.cardNumber,
        ...(c.story ? { story: c.story } : {}),
        ...(c.caption ? { caption: c.caption } : {}),
      });
    }
    return { slug: deck.slug, cards: sorted.length };
  },
});

// Orchestrator: wipe, then import each deck in its own transaction.
export const run = internalAction({
  args: {},
  handler: async (ctx) => {
    // Safety: refuse to wipe + import if the catalog still has placeholder URLs
    // (i.e. build-catalog.mjs was run without the real R2_PUBLIC_BASE_URL).
    const sample = catalog.decks[0]?.cards[0]?.imageUrl ?? "";
    if (!sample.startsWith("http") || sample.includes("PLACEHOLDER")) {
      throw new Error(
        "catalogData.ts has placeholder/invalid image URLs. Regenerate with the real " +
          "R2 base URL first:  npm run images:catalog"
      );
    }

    let wiped = 0;
    let batch;
    do {
      batch = await ctx.runMutation(internal.importCatalog.wipeBatch, {});
      wiped += batch.deleted;
    } while (batch.deleted > 0);

    const results = [];
    for (let i = 0; i < catalog.decks.length; i++) {
      results.push(
        await ctx.runMutation(internal.importCatalog.importOneDeck, { deckIndex: i })
      );
    }
    const cards = results.reduce((s, r) => s + r.cards, 0);
    console.log(`Imported ${results.length} decks / ${cards} cards (wiped ${wiped}).`);
    return { wiped, decks: results.length, cards };
  },
});
