// Merge the image manifest + parsed text into convex/catalogData.ts.
//
//   node --env-file=.env.local scripts/build-catalog.mjs
//
// Needs R2_PUBLIC_BASE_URL (to bake absolute image URLs). Images are the source of
// truth for which cards exist; text enriches them. Emits a typed TS module the Convex
// importer imports directly (no CLI arg passing).

import fs from "node:fs";
import {
  IMAGES_MANIFEST,
  TEXT_CATALOG,
  CATALOG_DATA_TS,
  FLAT_DECKS,
  WISDOM_DECKS,
  EXPECTED_DECKS,
  EXPECTED_CARDS,
  getR2Env,
} from "./config.mjs";

const { publicBaseUrl } = getR2Env(["publicBaseUrl"]);

function firstSentence(s) {
  if (!s) return "";
  const m = s.match(/^.*?[.!?](\s|$)/);
  const out = (m ? m[0] : s).trim();
  return out.length > 140 ? out.slice(0, 137).trimEnd() + "…" : out;
}

function main() {
  if (!fs.existsSync(IMAGES_MANIFEST))
    throw new Error(`Missing ${IMAGES_MANIFEST} — run optimize-images.mjs first`);
  if (!fs.existsSync(TEXT_CATALOG))
    throw new Error(`Missing ${TEXT_CATALOG} — run parse-markdown.mjs first`);

  const manifest = JSON.parse(fs.readFileSync(IMAGES_MANIFEST, "utf8"));
  const text = JSON.parse(fs.readFileSync(TEXT_CATALOG, "utf8"));
  const manifestBySlug = new Map(manifest.decks.map((d) => [d.slug, d]));

  const warnings = [];
  const decks = [];

  for (const cfg of [...FLAT_DECKS, ...WISDOM_DECKS]) {
    const m = manifestBySlug.get(cfg.slug);
    if (!m || m.cards.length === 0) {
      warnings.push(`[${cfg.slug}] no images in manifest — deck skipped`);
      continue;
    }
    const textCards = text[cfg.slug]?.cards ?? {};

    const cards = [...m.cards]
      .sort((a, b) => a.cardNumber - b.cardNumber)
      .map(({ cardNumber, key }) => {
        const t = textCards[cardNumber];
        if (!t) warnings.push(`[${cfg.slug}] card #${cardNumber} has image but no text`);
        const enHeadline = t?.enHeadline?.trim();
        const enTitle = t?.enTitle?.trim();
        const quote = enHeadline || enTitle || `Card ${cardNumber}`;
        const description = enTitle || firstSentence(t?.storyEn) || quote;
        const card = { imageUrl: `${publicBaseUrl}/${key}`, quote, description, cardNumber };
        if (t?.storyEn) card.story = t.storyEn;
        if (t?.captionEn) card.caption = t.captionEn;
        return card;
      });

    // Flag text-without-image (informational; dropped).
    const imageNums = new Set(m.cards.map((c) => c.cardNumber));
    for (const n of Object.keys(textCards)) {
      if (!imageNums.has(Number(n)))
        warnings.push(`[${cfg.slug}] card #${n} has text but no image (dropped)`);
    }

    decks.push({
      slug: cfg.slug,
      title: cfg.title,
      description: cfg.description,
      coverImageUrl: m.coverKey ? `${publicBaseUrl}/${m.coverKey}` : "",
      category: cfg.category,
      colorTheme: cfg.colorTheme,
      isActive: true,
      totalCards: cards.length,
      cards,
    });
    if (!m.coverKey) warnings.push(`[${cfg.slug}] no cover image (coverImageUrl empty)`);
  }

  const totalCards = decks.reduce((s, d) => s + d.cards.length, 0);

  const header =
    "// AUTO-GENERATED by scripts/build-catalog.mjs — DO NOT EDIT.\n" +
    "// Regenerate with: node --env-file=.env.local scripts/build-catalog.mjs\n" +
    "/* eslint-disable */\n\n" +
    "export type CatalogCard = {\n" +
    "  imageUrl: string;\n  quote: string;\n  description: string;\n" +
    "  story?: string;\n  caption?: string;\n  cardNumber: number;\n};\n\n" +
    "export type CatalogDeck = {\n" +
    "  slug: string;\n  title: string;\n  description: string;\n  coverImageUrl: string;\n" +
    "  category: string;\n  colorTheme: string;\n  isActive: boolean;\n  totalCards: number;\n" +
    "  cards: CatalogCard[];\n};\n\n";

  const body =
    "export const catalog: { decks: CatalogDeck[] } = " +
    JSON.stringify({ decks }, null, 2) +
    ";\n";

  fs.writeFileSync(CATALOG_DATA_TS, header + body);

  // ---- Summary ----
  for (const d of decks) {
    console.log(`  ${d.slug.padEnd(36)} ${String(d.totalCards).padStart(3)} cards`);
  }
  console.log(`\nDecks: ${decks.length} (expected ${EXPECTED_DECKS})`);
  console.log(`Cards: ${totalCards} (expected ${EXPECTED_CARDS})`);
  console.log(`Base URL: ${publicBaseUrl}`);
  if (warnings.length) {
    console.log(`\nWarnings (${warnings.length}):`);
    for (const w of warnings.slice(0, 40)) console.log(`  ! ${w}`);
    if (warnings.length > 40) console.log(`  ... and ${warnings.length - 40} more`);
  }
  if (decks.length !== EXPECTED_DECKS || totalCards !== EXPECTED_CARDS) {
    console.log(`\n⚠  Count mismatch — review warnings before importing.`);
  }
  console.log(`\nWrote ${CATALOG_DATA_TS}`);
}

main();
